# _author: Coke
# _date: 2022/7/20 12:19

from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver import Remote


class Selenium:
    """ selenium api 基础封装 """

    def __init__(self, driver: Remote):
        self.driver = driver

    def find_elements(self, by, value) -> list[WebElement]: ...

    def find_elements_click(self, by, value, index=0, name=None) -> None: ...

    def find_elements_clear(self, by, value, index=0, name=None) -> None: ...

    def find_elements_send_keys(self, by, value, content, index=0, name=None) -> None: ...

    def get_window_size(self) -> tuple: ...

    def wait_elements_appear(self, by, value, index=0, name=None, wait_time=5, interval=0.5) -> tuple[bool, str]: ...

    def find_elements_location(self, by, value, index=0, name=None) -> tuple[int, int]: ...

    def find_elements_size(self, by, value, index=0, name=None) -> tuple[int, int]: ...

    def screenshots(self, file_path=None, is_compression=True) -> str: ...

    def find_elements_screenshots(self, by, value, index=0, name=None, file_path=None, is_compression=False) -> str: ...
